### ISSUE TITLE
Document Uploader App

### ISSUE THREAD

**Issue by cheesteban** [doh-eb/CDRS#2]
**Is your feature request related to a problem? Please describe.**
The web UI is not so convenient to use when uploading many files.

**Describe the solution you'd like**
There should be an app that will automatically get documents from a local folder and upload to CDRS.

**Comment by freds-filinvestcity** [comment]
Assigned to @freds-filinvestcity

**Comment by cheesteban** [comment]
Thank you Sir Fred!

**Comment by freds-filinvestcity** [comment]
Initial version has been uploaded to GitHub in [92e90bf](https://github.com/doh-eb/CdrsUploader/commit/92e90bf1060201eea9a6267c66f59ecacedc1645). Testing by DOH-EB is ongoing.

**Comment by freds-filinvestcity** [comment]
Uploader has been deployed to St Luke's QC and St Luke's BGC. Closing this issue.
