### ISSUE TITLE
Interface with COVID KAYA

### ISSUE THREAD

**Issue by cheesteban** [doh-eb/CDRS#3]
**Is your feature request related to a problem? Please describe.**
Users need to upload to CDRS then entries need to be encoded in COVID Kaya.

**Describe the solution you'd like**
CDRS should be able to upload the entries automatically to COVID Kaya.

**Comment by pczuniga** [comment]
FHIR APIs are already available in:
(test server):  https://www.notion.so/COVID-Kaya-API-Documentation-e5767dd04aab412688e3305fd96366bd
mapping between old payload to FHIR - APIs:  https://docs.google.com/spreadsheets/u/2/d/1W3DxVs7mPUkS_je55UEfz_RdwtUPc2wIYFXnImdRpy0/edit?fbclid=IwAR2WCgm1BVFCrRf4mOnrhWdhjeXiqacO19z-6W4cweMV8MdUtY34utICt2s#gid=0
