### ISSUE TITLE
Process/validation for "Skip" option under Encode tab

### ISSUE THREAD

**Issue by JustineKim17** [doh-eb/CDRS#32]
Validations for each option in the drop-down and destination of the uploaded file for each option

**Comment by flabbyPatty** [comment]
@JustineKim17 there's not much detail here. Please elaborate.

**Comment by JustineKim17** [comment]
Hi, @flabbyPatty 

Everytime an encoder will "Skip" a document (CIF/Lab Result), they will be asked for a reason. For example, if the encoder will choose "Unreadable", the uploaded document will stay in the loop in order for other encoders to encode the document.

However, if other reasons were chosen i.e. "Missing Information", will the document stay in the loop or will be stored in a different location knowing that the document is "rejected"? It seems possible that Skips are numbered but the document still stays in the loop.

This question was raised from the Data Collection Section.

**Comment by dabe03** [comment]
hi sir @JustineKim17 ,

Walang pong looping na nangyayari sa mga skipped documents po. Once na ma skip sya regardless sa reason, rejected na po yung document na yun. 

Ang skipped reason po ay para lang po ma identify lang kung document bakit po rejected.

**Comment by JustineKim17** [comment]
Thank you for this confirmation, @dabe03!
