### ISSUE TITLE
Support for extracting information from lab results of additional laboratories

### ISSUE THREAD

**Issue by cheesteban** [doh-eb/CDRS#4]
**Is your feature request related to a problem? Please describe.**
CDRS is able to automatically extract information from lab results from RITM, PRC and San Lazaro but for others, they still have to be manually encoded.

**Describe the solution you'd like**
CDRS should add support for extractinng information from the ff labs.
- Bataan General Hospital
- Clinical Genomics
- Jose Lingad Memorial General Hospital
- Marikina Molecular Diagnostic Laboratory
- NKTI Medical Laboratory
- Singapore Medical Laboratories
- Saint Lukes Medical Center
- Victoriano Luna Medical Center
- Zamboanga City Medical Center

**Comment by freds-filinvestcity** [comment]
Assigned to @supersam-filinvestcity

**Comment by cheesteban** [comment]
Thank you Sir Fred!
