### ISSUE TITLE
View restriction

### ISSUE THREAD

**Issue by cheesteban** [doh-eb/CDRS#9]
Allow view:
1. per lab
2. per facility
3. per LGU

**Comment by freds-filinvestcity** [comment]
CDRS will filter search results based on the user's region/province/city/facility/lab/msf

**Comment by cheesteban** [comment]
Thank you Sir Fred!

**Comment by freds-filinvestcity** [comment]
This is already deployed in [1.8.0](https://github.com/doh-eb/CDRS.Web/releases/tag/1.8.0)
